### ISSUE TITLE
Chrome on Windows, script works less often than it fails

### ISSUE THREAD

**Issue by Marco-PF2** [wattsoner/Vine-Review-Helper#1]
Already reported this on Discord, just putting here FYI.

I'm on the USA server and for some reason the script doesn't usually work (it doesn't give me the buttons) when I first open a review page.  It will often not work after I refresh a few times.  But eventually, without doing anything but refreshing the page, it will work.  And, by "work" I mean I have the special buttons that do their thing. I did try disabling and re-enabling the script with the tampermonkey button.  Didn't hurt anything but didn't help (consistently) either.  I did make sure that I was up-to-date at this point too, before these results.

The good news is that it worked 7 times so I have seven reviews archived.  w00t!!!

**Comment by Marco-PF2** [comment]
Does this mean anything?

![Screenshot 2024-02-29 043419](https://github.com/wattsoner/Vine-Review-Helper/assets/128917779/6693e1e4-a7b0-4010-9fd3-eb0daab32775)

**Comment by wattsoner** [comment]
hopefully should be fixed now, it works on my end, please update & get back to me

**Comment by Marco-PF2** [comment]
Fixed!
