### ISSUE TITLE
Prevent archiving incomplete review 

### ISSUE THREAD

**Issue by Marco-PF2** [wattsoner/Vine-Review-Helper#2]
Enhancement request posted in [Discord](https://discord.com/channels/1076155409481601044/1212532533707669524/1213627613453746176):  

Around maybe line 193, if any of the following are true:  
- `starCount = 0`  
- `headline = ""`  
- `reviewText = ""`  

Then `alert("Not Sent: Review form incomplete."); return`

**Comment by Marco-PF2** [comment]
![Screenshot_20240302-194421.png](https://github.com/wattsoner/Vine-Review-Helper/assets/128917779/ed4f37e2-ec92-49b4-9781-85cea8c8bb5b)

**Comment by Marco-PF2** [comment]
> Enhancement request posted in [Discord](https://discord.com/channels/1076155409481601044/1212532533707669524/1213627613453746176):  
> 
> Around maybe line 193, if any of the following are true:  
> - `starCount = 0`  
> - `headline = ""`  
> - `reviewText = ""`  
> 
> Then `alert("Not Sent: review incomplete."); return` 
> 

![Screenshot_20240302-194421.png](https://github.com/wattsoner/Vine-Review-Helper/assets/128917779/e4abcc16-d55a-433b-ac86-26ffd12e3b4f)

**Comment by wattsoner** [comment]
![0 1 4 - 1](https://github.com/wattsoner/Vine-Review-Helper/assets/114074290/afa721e5-3812-4cc7-96bc-dbd2e38e7c77)
![0 1 4 - 2](https://github.com/wattsoner/Vine-Review-Helper/assets/114074290/6b94b303-7ff0-4120-bbf3-93cae1df835c)


done 👍

**Comment by wattsoner** [comment]
closed

**Comment by Marco-PF2** [comment]
![Screenshot_20240302-194421.png](https://github.com/wattsoner/Vine-Review-Helper/assets/128917779/ed4f37e2-ec92-49b4-9781-85cea8c8bb5b)

    Lol oooh you got all FancyLike 😁

Tyty & well-done!!!

**Comment by Marco-PF2** [comment]
> ![0 1 4 - 1](https://github.com/wattsoner/Vine-Review-Helper/assets/114074290/afa721e5-3812-4cc7-96bc-dbd2e38e7c77)
> ![0 1 4 - 2](https://github.com/wattsoner/Vine-Review-Helper/assets/114074290/6b94b303-7ff0-4120-bbf3-93cae1df835c)
> 
> 
> done 👍

Oooh! You got all FancyLike 😁

Tyty & very well-done!!
